version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s %(process)d|%(thread)d %(levelname)s [%(filename)s<%(funcName)s, %(lineno)d>] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file:
    (): CalcTool.sdk.logger.Logger.log_maker
    level: DEBUG
    formatter: simple
loggers:
  root:
    level: INFO
    handlers: [console, file]
    propagate: no